### ISSUE TITLE
TODO: Reslice cursor widget

### ISSUE THREAD

**Issue by laurennlam** [Kitware/vtk-js#1728]
Here is a list of enhancements for the reslice cursor widget:

- [ ] Image reslice in GPU
- [ ] Add image slab
- [ ] Separate updateReslicePlane into two functions because the current implementation is limited. We cannot iinstanciate only two view, then rotate in one, and create the third one. The viewUp won't be correct on the third one because now, the view up used the previous view up value.

@finetjul

**Comment by finetjul** [comment]
"Add image slab" is handled by #1727

**Comment by agirault** [comment]
VolumeMapper with clipping panes can be used for image reslice in GPU (see interactorstyleMPR)
