### ISSUE TITLE
WebGPU ToDo tasks

### ISSUE THREAD

**Issue by jadh4v** [Kitware/vtk-js#2227]
### Need

Address WebGPU to-do list here:
https://github.com/Kitware/vtk-js/tree/master/Sources/Rendering/WebGPU#todo

# ToDo
- [ ] Add device.lost handler.
- [ ] Create background class to encapsulate, background clear, gradient background, texture background, skybox etc.
- [ ] PBR lighting to replace the simple model currently coded.
- [ ] Eventually switch to using IBOs and flat interpolation.
- [ ] Cropping planes for polydata, image, volume mappers.
- [ ] Update widgets to use the new async hardware selector API.
- [ ] Add rgb texture support to volume renderer.
- [ ] Add lighting to volume rendering.
- [ ] Add line zbuffer offset to handle coincident.
- [ ] Possibly change the zbuffer equation to be linear float30.

Waiting on fixes/dev in WebGPU spec:
- [ ] more cross platform testing and bug fixing, firefox and safari

**Comment by jadh4v** [comment]
@floryst @martinken 
Issue created to track To-Do list of WebGPU features.

**Comment by daker** [comment]
@jadh4v i have a PR for Cropping planes if you want to check it PR #3464
